initial_file = "initial.txt"
encrypted_file = "encrypted.txt"
decrypted_file = "decrypted.txt"
symmetric_key = "encrypted_symmetric_key.bin"
public_key = "public_key.pem"
secret_key = "private_key.pem"
